name: 'Test Composite Action'
description: 'Create Component Version, Add Version Link, Add Version Files, Add Version Properties'
inputs:
  component:
    description: 'Component Name/ID'
    required: true
  versionname:
    description: 'Component Version Name'
    required: true
  description:
    description: 'Component version description'
    required: false
  link:
    description: 'URL to add to component version'
    required: false
  base:
    description: 'Local base directory containing files to upload if file upload is required'
    required: false
    default: ""
  offset:
    description: 'Target path offset (the directory in the version files to which these files should be added)'
    required: false
    default: ""
  include:
    description: 'An include file pattern for selecting files to add (may be repeated)'
    required: false
    default: "*"
  exclude:
    description: 'An exclude file pattern for excluding files (may be repeated). Overrides includes.'
    required: false
    default: ""
  saveExecuteBits:
    description: 'Saves execute bits for files.'
    required: true
    type: boolean
    default: false
  hostname:
    description: 'DevOps Deploy hostname'
    required: true
  port:
    description: 'port'
    required: true
    default: '8443'
  username:
    description: 'username'
    required: false
  password:
    description: 'password'
    required: false
    secret: true
  authToken:
    description: 'DevOps Deploy authentication token'
    required: false
    secret: true
  disableSSLVerification:
    description: 'skip SSL certificate validation when making HTTPS requests and this is discouraged'
    required: true
    type: boolean
    default: false
runs:
  using: "composite"
  steps:
    # Download udclient package from composite action github repository
    - uses: actions/checkout@v4
      with:
        repository: jwcarmichael12/test-composite-action
        sparse-checkout: |
          artifacts/devops-deploy-client.zip
        sparse-checkout-cone-mode: false
        path: tools
        
    # Setup java environment needed to run the udclient
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt-openj9' # See 'Supported distributions' for available options
        java-version: '11'
        
    # Expand the udclient package to access the executable
    - name: Install udclient
      id: udclient-install
      run: unzip tools/artifacts/devops-deploy-client.zip
      shell: bash
      
    # Create component version
    - name: Create component version
      id: create-component-version
      run: udclient/udclient createVersion -component "${{ inputs.component }}" -name "${{ inputs.versionname }}"  --importing true
      shell: bash
      env:
        DS_WEB_URL: https://${{ inputs.hostname }}:${{ inputs.port }}
        DS_AUTH_TOKEN: ${{ inputs.authtoken }}

    # Add Version Link if one is specified
    - name: Add component version link
      id: add-version-link
      if: ${{ inputs.link }}
      run: udclient/udclient addVersionLink -component "${{ inputs.component }}" -version "${{ inputs.versionname }}" -linkName "Git commit" -link "${{ inputs.link }}"
      shell: bash
      env:
        DS_WEB_URL: https://${{ inputs.hostname }}:${{ inputs.port }}
        DS_AUTH_TOKEN: ${{ inputs.authtoken }}

    # Add Version Files if specified
    - name: Add component version files
      id: add-version-files
      if: ${{ inputs.base }}
      run: |
        udclient/udclient addVersionFiles -component "${{ inputs.component }}" -version "${{ inputs.versionname }}" -base  "${{ inputs.base }}" -offset "${{ inputs.offset }}" -include "${{ inputs.include }}" -exclude "${{ inputs.exclude }}" -saveExecuteBits ${{ inputs.saveExecuteBits }}
      shell: bash
      env:
        DS_WEB_URL: https://${{ inputs.hostname }}:${{ inputs.port }}
        DS_AUTH_TOKEN: ${{ inputs.authtoken }}
      
    # Tell devops deploy server that component version creation is complete
    - name: Finish Importing
      id: finish-importing
      run: udclient/udclient finishedImporting -component "${{ inputs.component }}" -version "${{ inputs.versionname }}"
      shell: bash
      env:
        DS_WEB_URL: https://${{ inputs.hostname }}:${{ inputs.port }}
        DS_AUTH_TOKEN: ${{ inputs.authtoken }}
        
