name: 'Test Composite Action'
description: 'Figure out how this works'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: jwcarmichael12/test-composite-action
        sparse-checkout: |
          artifacts/devops-deploy-client.zip
        sparse-checkout-cone-mode: false
        path: tools
    - name: setup udclient
      id: udclient-setup
      run: ls -la &ls -la tools&unzip tools/artifacts/devops-deploy-client.zip&ls -la tools/artifacts
      shell: bash
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
