name: 'Test Composite Action'
description: 'Figure out how this works'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: jwcarmichael12/test-composite-action
        sparse-checkout: |
          artifacts/devops-deploy-client.zip
        sparse-checkout-cone-mode: false
        path: tools
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt-openj9' # See 'Supported distributions' for available options
        java-version: '11'
    - name: install udclient
      id: udclient-install
      run: ls -la &ls -la tools&unzip tools/artifacts/devops-deploy-client.zip&ls -la tools/artifacts
      shell: bash
    - name: run udclient
      id: udclient-run
      run: tools/artifacts/udclient
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
